### ISSUE TITLE
Problem when sending

### ISSUE THREAD

**Issue by GateroChannel** [redteamsecurity/PyPhishing#2]
Hello guys, i recently found out about you and your work and i got really interested. I tried to use this Python Script to see what it is about but i am having problems to use it. After i configurate all the necesary fields when i try to Test or Send i get this error.
`Time started: 
03:13:

Traceback (most recent call last):
  File "./pyPhishing.py", line 480, in <module>
    deliverEmails.deliverance(argument_dict)
  File "/root/PyPhishing/PyPhishing/SupportingFiles/deliverEmails.py", line 135, in deliverance
    message, email_id = build_email(address, variable_dict)
  File "/root/PyPhishing/PyPhishing/SupportingFiles/deliverEmails.py", line 39, in build_email
    oldBody = body_file.build_body(temp_dict)
  File "/root/PyPhishing/PyPhishing/SupportingFiles/Emails/microsoftUpdateBody.py", line 101, in build_body
    img_data = open(img_location, 'rb').read()
IOError: [Errno 2] No such file or directory: '/root/PyPhishing/PyPhishing/SupportingFiles/images/microsoft.png'
`

**Comment by deepseasred** [comment]
Apologies GateroChannel, 

I didn't add or commit the images directory to the master branch (fail). Everything should be added now, please let me know if there are more issues. I appreciate the feedback!

**Comment by GateroChannel** [comment]
Wow thanks for your fast reply, ill try it right now. And thanks to you for shareing this.

**Comment by GateroChannel** [comment]
Sorry to spam here, but i dont wanna create a post for every error. Now that error is fixed but im getting a new one. Im getting this error now. I tried with both gmail and hotmail.
`
Error: unable to send email to ********************@hotmail.com

Error: unable to send email to ************************@gmail.com

`

**Comment by deepseasred** [comment]
No worries, I look forward to the spam! Would you be able to go into the advance settings (option 5) and "set verbose true" so I can see what the SMTP server sees and is potentially blocking? Make sure you look through the output and blur out any credentials if any are posted.

**Comment by GateroChannel** [comment]
Well i manage to fixed it see that logs, it was only a misconfiguration with the smtp credentials, the thing is that i received the message but the sender email appeared as mine, there is a way to hide this?
Also the link in the email does something or is just a microsoft link?

**Comment by deepseasred** [comment]
It really is based upon the email configuration of the server but you can try to set the 'smtpfrom' and/or the 'headerfrom' variables in the advanced settings to gain different results. The smtpfrom is what the actual SMTP server sees as the 'RCPT To:' command and the headerfrom is what the email application will see when it renders the data portion of the email.

**Comment by GateroChannel** [comment]
i set Microsoft Update update@microsoft.com to headerfrom and update@microsoft.com to smtpfrom but i still recive the emails from my hotmail account

**Comment by deepseasred** [comment]
It would help immensely if you were able to post the verbose info from the server. That would help me see all the settings and also see how the server reacts to such settings.
